package langchainkt.model.output

/**
 * Represents the response from various types of models, including language, chat, embedding, and moderation models.
 * This class encapsulates the generated content, token usage statistics, and finish reason.
 *
 * @param <T> The type of content generated by the model.
</T> */
data class Response<T>(
  private val content: T,
  private val tokenUsage: TokenUsage? = null,
  private val finishReason: FinishReason? = null
) {

  fun content(): T {
    return content
  }

  fun tokenUsage(): TokenUsage? {
    return tokenUsage
  }

  fun finishReason(): FinishReason? {
    return finishReason
  }

  companion object {
    fun <T> from(content: T): Response<T> {
      return Response(content)
    }

    fun <T> from(content: T, tokenUsage: TokenUsage?): Response<T> {
      return Response(content, tokenUsage, null)
    }

    fun <T> from(content: T, tokenUsage: TokenUsage?, finishReason: FinishReason?): Response<T> {
      return Response(content, tokenUsage, finishReason)
    }
  }
}
